###Obtener todos los Empleados
GET http://localhost:3000/api/empleado

###Crear Empleado
POST http://localhost:3000/api/empleado
Content-Type: application/json

{
    "IdEmpleado":1221100262,
    "Nombre": "Juan Pablo Jimenez Jaime",
    "Edad": 19,
    "Rol": ["Administrador","Mantenimiento"],
    "Telefono": [4151331602, 4151672436],
    "Sueldo": 10000.00,
    "Turno": "Matutino",
    "Correo": "Juanpij23@hotmail.com",
    "Contraseña": "linux"
}

###Obtener Empleado por ID
GET http://localhost:3000/api/empleado/63ffbdd44e8c96c0c60f038d

###Eliminar Empleado por ID
DELETE http://localhost:3000/api/empleado/63ffbdd44e8c96c0c60f038d

###Obtener Empleado por IdEmpleado
GET http://localhost:3000/api/empleado/IdEmpleado/1221100262

###Actualizar Empleado
PUT http://localhost:3000/api/empleado/63ffbdd44e8c96c0c60f038d
Content-Type: application/json

{
    "IdEmpleado":1221100262,
    "Nombre": "Jose Juan",
    "Edad": 19,
    "Rol": ["Mantenimiento"],
    "Telefono": [4151331602],
    "Sueldo": 8000.00,
    "Turno": "Vespertino",
    "Correo": "Juanpij23@hotmail.com",
    "Contraseña": "linux"
}