###Obtener todos los Menus
GET http://localhost:3000/api/menu

###Crear Menu
POST http://localhost:3000/api/menu
Content-Type: application/json

{
    "IdMenu": 1,
    "Nombre": "Administrador",
    "Privilegios": ["CRUD-Empleado","CRUD-Clases"]
}

###Obtener Menu por ID
GET http://localhost:3000/api/menu/6400f6e04ea71d71f2a8c5fa

###Eliminar Menu por ID
DELETE http://localhost:3000/api/menu/6400f6e04ea71d71f2a8c5fa

###Obtener Menu por IdMenu
GET http://localhost:3000/api/menu/IdMenu/1

###Actualizar Menu
PUT  http://localhost:3000/api/menu/63ffc9890a74de6c46f763fc
Content-Type: application/json

{
    "IdMenu": 1,
    "Nombre": "Administrador",
    "Privilegios": ["Actualizar Empleado","Obtener Empleado"]
}